name: surge workflow

on: push

jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to miineidi.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "https://miineidi.surge.sh"
          project: "."
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
